name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.8.0

    - name: Compile
      env:
        BUILD_TYPE: ${{  github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}
      run: |
          if ($env:BUILD_TYPE -eq "Debug") {
            cl /EHsc /Zi /Fe:leetcode_build_debug.exe main.cpp CommonFunction.cpp RemovElement.cpp RemoveDuplicatesSortedArray.cpp RemoveLinkedListElement.cpp ReverseString.cpp SingleNumber.cpp
          } else {
            cl /EHsc /O2 /DNDEBUG /Fe:leetcode_build_release.exe main.cpp TwoSum.cpp CommonFunction.cpp RemovElement.cpp RemoveDuplicatesSortedArray.cpp RemoveLinkedListElement.cpp ReverseString.cpp SingleNumber.cpp
          }
          
    - name: Run Executable
      env:
        BUILD_TYPE: ${{ github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}
      run: |
        if ($env:BUILD_TYPE -eq "Debug") {
          ./leetcode_build_debug.exe
        } else {
          ./leetcode_build_release.exe
        }

    - name: Artifact Upload
      uses: actions/upload-artifact@v2
      with:
        name: leetcode-executable-${{ env.BUILD_TYPE }}
        path: leetcode_build*.exe
